---
- name: "deploy centos9 to aws"
  hosts: "localhost"
  gather_facts: false
  connection: local
  become: false
  vars:
    ec2_instance_test_name: minimal
    vpc_subnet_id: "subnet-05bb445fa8e383722"
  roles:
    - { role: ec2_instance }
