---
- name: "deploy centos9 to aws"
  hosts: "localhost"
  gather_facts: false
  connection: local
  become: false
  vars:
    ec2_instance_test_name: minimal
    vpc_subnet_id: "subnet-05bb445fa8e383722"
    centos9_ami: "ami-0d55375e7a00f3332"
  
  environment:
    AWS_REGION: "eu-west-2"
  roles:
    - { role: ec2_instance }
