---
- name: "remove all instance from aws"
  hosts: "localhost"
  gather_facts: false
  connection: local
  become: false
  vars:
    ec2_instance_test_name: minimal
    vpc_subnet_id: "subnet-05bb445fa8e383722"
  environment:
    AWS_REGION: "eu-west-2"
  tasks:
    - name: "Terminate every running instance in a region. Use with EXTREME caution"
      amazon.aws.ec2_instance:
        state: absent
        filters:
          instance-state-name: running
