---

- name: "Call aws_az_info"
  amazon.aws.aws_az_info:
  register: result_az_info

- name: "Get called information"
  amazon.aws.aws_caller_info:
  register: result_account_info

- name: "Display aws info "
  ansible.builtin.debug:
    msg:
      - "AWS INFO: {{result_az_info }}"
      - "AWS ACCOUNT INFO: {{ result_account_info }}"
