---
# code: language=ansible


- name: "Call aws_az_info"
  amazon.aws.aws_az_info:
  register: result_az_info

- name: "Get called information"
  amazon.aws.aws_caller_info:
  register: result_account_info

- name: "Display aws info"
  ansible.builtin.debug:
    msg:
      - "AWS INFO: {{ result_az_info }}"
      - "AWS ACCOUNT INFO: {{ result_account_info }}"

- name: "Create a new instance"
  amazon.aws.ec2_instance:
    name: "{{ ec2_instance_test_name  }}"
    security_group: default
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    network:
      assign_public_ip: true
    image_id: '{{ centos9_ami }}'
    key_name: '{{ aws_keypar }}'
    instance_type: "{{ec2_instance_type}}"
    tags:
      Environment: Testing
