---
- name: "Latest Apache version installed"
  ansible.builtin.yum:
    name: httpd
    state: latest
  notify: apache-restart

- name: "Latest firewalld version installed"
  ansible.builtin.yum:
    name: firewalld
    state: latest

- name: "Firewalld enabled and running"
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started

- name: "Firewalld permits http service"
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: "Apache enabled and running"
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started

- name: Ensure proper Apache configuration
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  notify: apache-restart

- name: deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: apache-restart
